repos:
  - repo: git://github.com/dnephin/pre-commit-golang
    sha: v0.2
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-lint
      - id: validate-toml
      - id: no-go-testing
      - id: gometalinter
